name: ⚙️ CI Backend

on:
  push:
  #    branches: [ "*" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
      kafka:
        image: wurstmeister/kafka
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
          KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        ports:
          - 9092:9092
    env:
      TZ: 'Asia/Seoul'
      MYSQL_HOST: localhost
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #      AWS_REGION: ${{ secrets.AWS_REGION }}
      #      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    steps:
      # 1. 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. 시간 설정
      - name: Check the timezone
        run: date

      # 3. 자바 버전 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. firebase json 파일 생성
      - name: Generate firebase_account.json
        run: |
          mkdir -p ./core/src/main/resources/firebase
          echo "${{ secrets.FIREBASE_ACCOUNT }}" | base64 -d > ./core/src/main/resources/firebase/firebase_account.json          
          mkdir -p ./core/src/test/resources/firebase
          echo "${{ secrets.FIREBASE_ACCOUNT }}" | base64 -d > ./core/src/test/resources/firebase/firebase_account.json
          mkdir -p ./api/src/test/resources/firebase
          echo "${{ secrets.FIREBASE_ACCOUNT }}" | base64 -d > ./api/src/test/resources/firebase/firebase_account.json

      # 5. gradle 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 6. 빌드 시 의존성 캐싱
      - name: Caching gradle
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 7. 빌드 & JaCoCo 리포트 생성
      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport --build-cache --parallel

      # 8. 테스트 결과 PR 코멘트에 등록
      - name: Register the test results as PR comments
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      # 9. 테스트 실패시 코드 라인에 대한 체크 추가
      - name: If test fail, add check comment on failed code line
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.html'

      - name: Checkout source code
        uses: actions/checkout@v3

      #      # 10. JaCoCo 리포트 생성
      #      - name: Generate JaCoCo Report
      #        run: ./gradlew test jacocoTestReport

      # 10. Codecov 업로드
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '**/build/reports/jacoco/test/jacocoTestReport.xml'
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: false